name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 12.X
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile

      - run: yarn audit:ci

      - run: yarn lint
      - run: yarn lint:copyright ${{ github.workspace }}/*/**.{js,ts,tsx}
      - run: yarn build
      - run: yarn build-storybook

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 12.X
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile

      - run: yarn test --coverage

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1.16
        if: always()
        with:
          files: 'coverage/junit.xml'
          comment_mode: off
          check_name: 'Test results'
          fail_on: 'nothing'

  visual-test:
    name: Run visual tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 12.X
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile

      # `&` symbol is needed as it prevents Storybook from running endlessly
      - run: yarn storybook &
      - run: yarn creevey
