name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 16.X
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn audit

      - run: yarn lint
      - run: yarn workspace @itwin/itwinui-react lint:copyright ${{ github.workspace }}/*/**.{js,ts,tsx}
      - run: yarn build
      - run: yarn workspace @itwin/itwinui-react build-storybook

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 16.X
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn workspace @itwin/itwinui-react test --coverage

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1.16
        if: always()
        with:
          files: 'packages/iTwinUI-react/coverage/junit.xml'
          comment_mode: off
          check_name: 'Test results'
          fail_on: 'nothing'

  visual-test:
    name: Run visual tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 16.X
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn install --frozen-lockfile

      # `&` symbol is needed as it prevents Storybook from running endlessly
      - run: yarn workspace @itwin/itwinui-react storybook &
      - run: yarn workspace @itwin/itwinui-react creevey
