name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 16.X
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn audit

      - run: yarn lint
      - run: yarn lint:copyright
      - run: yarn build

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 16.X
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn workspace @itwin/itwinui-react test --coverage

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1.16
        if: always()
        with:
          files: 'packages/iTwinUI-react/coverage/junit.xml'
          comment_mode: off
          check_name: 'Test results'
          fail_on: 'nothing'

  visual-test:
    name: Run visual tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('apps/storybook/scripts/docker/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: docker/build-push-action@v2
        with:
          file: apps/storybook/scripts/docker/Dockerfile
          platforms: linux/amd64
          tags: itwinui/cypress:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          load: true

      - name: Use Node 16.X
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn test --filter=storybook

      - name: Publish test results artifact
        if: failure()
        uses: actions/upload-artifact@v3.0.0
        with:
          name: 'cypress-visual-screenshots'
          path: '${{ github.workspace }}/apps/storybook/cypress-visual-screenshots'
