name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://bentleycs.visualstudio.com/beconnect/
          azure-pipeline-name: 'iTwinUI Documentation Website'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
